// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgMLx4q6hBRKZ5USOQ1OQQGMynjMdXTI',
    appId: '1:148579580988:web:a4c270c2fda64747239739',
    messagingSenderId: '148579580988',
    projectId: 'itisummer-d1c79',
    authDomain: 'itisummer-d1c79.firebaseapp.com',
    storageBucket: 'itisummer-d1c79.appspot.com',
    measurementId: 'G-ZELBNYSZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKIEH2VJJ0_U4gw67kptyvLByhwbKYQM4',
    appId: '1:148579580988:android:9e7cdb96a548bfd4239739',
    messagingSenderId: '148579580988',
    projectId: 'itisummer-d1c79',
    storageBucket: 'itisummer-d1c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleTxU8NlKjF46ve-aB_83fuXZ8D5A-9Y',
    appId: '1:148579580988:ios:e407cb415cf04d3a239739',
    messagingSenderId: '148579580988',
    projectId: 'itisummer-d1c79',
    storageBucket: 'itisummer-d1c79.appspot.com',
    iosClientId: '148579580988-i6ec23umrk25lsfbuqokjfoa7f2sv7rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterpro',
  );
}
